### ISSUE TITLE
Having trouble posting json content.

### ISSUE THREAD

**Issue by ober** [nicferrier/emacs-web#16]
Trying to post json payload and am able to get the results I want with the 'request' library, but can't seem to do the same with web.el.
Using https://github.com/ober/sumo-el with the test sinatra.rb file there the output is in test-output. There are two functions named sumo-add-source-to-id. One using web.el and one using request. Search for XXX for the invocation example.
Any ideas of what I am doing wrong?
So I need the content type to be application/json, AND the json contents in the body of the request. As seen from Sinatra.
Thanks for any help.
Web.el is a great library!

**Comment by ober** [comment]
This example also works the same way using curl.
curl -u "$auth" -X POST -H "Content-Type: application/json" -T nginx.json "http://localhost:4567/foo"

**Comment by nicferrier** [comment]
How do I run the sinatra?

**Comment by ober** [comment]
If you have rubygems
gem install sinatra

Then
ruby ./test.rb

**Comment by nicferrier** [comment]
Sorry this has taken so long to respond. Busy busy.

I did this:

``` emacs-lisp
(require 'elnode)
(defun sumo-handler (httpcon)
  (elnode-send-json httpcon '(a b c)))
(elnode-start 'sumo-handler :port 8003)

;; your code mangled a little
(let ((heads `(("Content-Type" . "application/json")
               ("Authorization"
                . ,(concat "Basic "
                           (base64-encode-string
                            (concat "nic" ":" "secret"))))))
      (url "http://localhost:8003/foo")
      (id 101011014)
      (to-send
       (json-encode
        '((source
           (pathExpression . "/tmp/test.log")
           (cutoffTimestamp . 0)
           (sourceType . "LocalFile")
           (name . "TestError"))))))
  (web-http-post
   (lambda (con header data)
     (message "%S" data))
   :url url
   :extra-headers heads
   :data to-send
   :mime-type "application/json"
   ))
```

This worked. I got back [a, b, c] from elnode. Which is what I should have got. So hum.

I haven't been able to install your sinatra yet.

Have you tried it with a dumber handler function like mine? Maybe web is doing something wrong with whatever sinatra sends? If you could message it then that would prove that either way. You could also copy the messaged output here and I could work out what it was.

**Comment by ober** [comment]
curl -H "Content-Type:application/json" -X POST http://httpbin.org/post
vs 
curl -H "Content-Type:application/json" -X POST -d "{ \ssources\":\"test\"}" http://httpbin.org/post

**Comment by nicferrier** [comment]
Oh right. Now I'm clear.

I looked. `web` does not send data unless it has a recognized mime-type:

https://github.com/nicferrier/emacs-web/blob/master/web.el#L581

I can alter that, I guess, so you can send anything. I'm not mad about doing that... why can't you just send what you want as parameters?

How would you suggest I changed the `web` api to allow arbitary data to be POSTed?

**Comment by ober** [comment]
I'm all for using json as you did in the example above. In testing it, I can't even get the to-send to be sent.

**Comment by ober** [comment]
Using http://hastebin.com/oqomoqevus I get http://hastebin.com/uxuxiradeb
Should it determine the type as json?
Or did I misread?

**Comment by nicferrier** [comment]
Well, that's right. As you can see `to-send` won't be sent unless you have a recognized data type. This is like jquery's ajax which won't send arbitary data either.

So I can patch web to allow any data to be sent by altering that case to have a default which is just:

```
(t data)
```

then it will work.

I'll do that in the next few days. Debugging marmalade right now.

**Comment by ober** [comment]
Thanks, I can patch for now.

**Comment by nicferrier** [comment]
I won't upload for a while, probably not till marmalade issues are ironed out.

**Comment by ober** [comment]
Thanks again!
