### ISSUE TITLE
Error: web/http-post-filter: Symbol's value as variable is void: hdr

### ISSUE THREAD

**Issue by ober** [nicferrier/emacs-web#17]
on ;; Version: 20140822.1831 of web.el

**Comment by nicferrier** [comment]
I don't get that. More info?

**Comment by ober** [comment]
Here is the backtrace on the lastest web.el 
if I comment out    (web/cookie-handler con hdr data) all is fine.

Debugger entered--Lisp error: (void-variable hdr)
  (web/cookie-handler con hdr data)
  (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse (buffer-substring ... ...))) (part-data (if (> ... ...) (buffer-substring ... ...) nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode)))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda (con data) (web/chunked-filter callback con mode header data))))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data))))
  (let ((header (process-get con :http-header))) (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse ...)) (part-data (if ... ... nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode)))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda (con data) (web/chunked-filter callback con mode header data))))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data)))))
  (save-current-buffer (set-buffer (process-buffer con)) (let ((header (process-get con :http-header))) (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char ...) (re-search-forward "
\n
\n" nil t))) (let ((hdr ...) (part-data ...)) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn ...))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda ... ...)))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data))))))
  web/http-post-filter(#<process web-http-post-foof.lighthouseapp.com:443//tickets.json?limit=100&q=responsible:me%20sort:priority%20state:new%20state:inactive%20state:active%20state:pending-review%20state:pending-approval><remove stuff>
  (progn (web/http-post-filter con part-data callback mode))
  (if part-data (progn (web/http-post-filter con part-data callback mode)))
  (let ((hdr (web-header-parse (buffer-substring (point-min) (point-max)))) (part-data (if (> (point-max) (point)) (buffer-substring (point) (point-max)) nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode))))
  (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse (buffer-substring (point-min) (point-max)))) (part-data (if (> (point-max) (point)) (buffer-substring (point) (point-max)) nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode)))))
  (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse (buffer-substring (point-min) (point-max)))) (part-data (if (> (point-max) (point)) (buffer-substring (point) (point-max)) nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode))))))
  (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse (buffer-substring ... ...))) (part-data (if (> ... ...) (buffer-substring ... ...) nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode)))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda (con data) (web/chunked-filter callback con mode header data))))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data))))
  (let ((header (process-get con :http-header))) (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char (point-min)) (re-search-forward "
\n
\n" nil t))) (let ((hdr (web-header-parse ...)) (part-data (if ... ... nil))) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn (web/http-post-filter con part-data callback mode)))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda (con data) (web/chunked-filter callback con mode header data))))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data)))))
  (save-current-buffer (set-buffer (process-buffer con)) (let ((header (process-get con :http-header))) (if (not header) (save-excursion (goto-char (point-max)) (insert data) (if (and (not header) (progn (goto-char ...) (re-search-forward "
\n
\n" nil t))) (let ((hdr ...) (part-data ...)) (process-put con :http-header-pos (point)) (process-put con :http-header hdr) (if part-data (progn ...))))) (web/cookie-handler con hdr data) (cond ((equal "chunked" (gethash (quote transfer-encoding) header)) (web/chunked-decode-stream con data (function (lambda ... ...)))) ((gethash (quote content-length) header) (web/content-length-filter callback con mode header data))))))
  web/http-post-filter(#<process web-http-post-foof.lighthouseapp.com:443//tickets.json?limit=100&q=responsible:me%20sort:priority%20state:new%20state:inactive%20state:active%20state:pending-review%20state:pending-approval> "HTTP/1.1 200 OK
\nCache-Control: private, max-age=0, must-revalidate
\nContent-Type: application/json; charset=utf-8
\nDate: Thu, 28 Aug 2014 01:18:32 GMT
\nETag: \"0b3e1e70a5cdd93f8943171a9abc1e87\"
\nServer: nginx
\nStatus: 200 OK
\nX-Content-Type-Options: nosniff
\nX-Frame-Options: SAMEORIGIN
\nX-Runtime: 181
\nX-XSS-Protection: 1; mode=block
\nContent-Length: 15877
\nConnection: keep-alive
\n

  #[514 "\301\300\302$\207" [(closure ((data ("X-LighthouseToken" . "")) (url . "https://foof.lighthouseapp.com//tickets.json?limit=100&q=responsible:me%20sort:priority%20state:new%20state:inactive%20state:active%20state:pending-review%20state:pending-approval") (extra . "limit=100&q=responsible:me%20sort:priority%20state:new%20state:inactive%20state:active%20state:pending-review%20state:pending-approval") (uri . "tickets.json") t) (httpc header my-data) (let\* ((old-dir default-directory) (buf (save-current-buffer (set-buffer ...) (prog1 ... ... ... ... ... ... ...))) (standard-output buf)) (prog1 (progn (switch-to-buffer-other-window "_lighthouse_") (mapcar (function lighthouse-print-url) (cdr ...))) (internal-temp-output-buffer-show buf)))) batch web/http-post-filter] 9 "\n\n(fn CON DATA)"](#<process web-http-post-foof.lighthouseapp.com:443//tickets.json?limit=100&q=responsible:me%20sort:priority%20state:new%20state:inactive%20state:active%20state:pending-review%20state:pending-approval> "HTTP/1.1 200 OK
\nCache-Control: private, max-age=0, must-revalidate
\nContent-Type: application/json; charset=utf-8
\nDate: Thu, 28 Aug 2014 01:18:32 GMT
\nETag: \"0b3e1e70a5cdd93f8943171a9abc1e87\"
\nServer: nginx
\nStatus: 200 OK
\nX-Content-Type-Options: nosniff
\nX-Frame-Options: SAMEORIGIN
\nX-Runtime: 181
\nX-XSS-Protection: 1; mode=block
\nContent-Length: 15877
\nConnection: keep-alive
\n
\n

**Comment by nicferrier** [comment]
pull again, someone else had the problem and I fixed it?

I also uploaded a new one to marmalade?
