### ISSUE TITLE
web-get not working.

### ISSUE THREAD

**Issue by arthurnn** [nicferrier/emacs-web#18]
Just installed emacs-web, and trying to do a simple `web-get`, but I am getting the error `error in process filter: Symbol's value as variable is void: hdr`.
Tried with multiple urls, no lucky. 
version: `web-20140824.1535`

**Comment by nicferrier** [comment]
Ah. Sorry. You used a broken package repository. The code in trunk isn't always releasable and yet certain package repositories like to package it up for your consumption anyway.

May I recommend a better package repository? one with less stuff in it but more stuff that actually works?

In less snarky comments I have fixed the problem. I guess you can just wait for the stupid (oops. sorry. snarky again) package repo to reissue it.

**Comment by nicferrier** [comment]
Or you could get the fixed version from [marmalade-repo](http://marmalade-repo.org/packages/web)

**Comment by arthurnn** [comment]
thanks for the fix.
